#!/bin/bash

WORK=25
PAUSE=5
INTERACTIVE=true
MUTE=false
potatofile="${XDG_DATA_HOME:-$HOME/.local/share}/pomodoro"

show_help() {
	cat <<-END
		usage: potato [-s] [-m] [-w m] [-b m] [-h]
		    -s: simple output. Intended for use in scripts
		        When enabled, potato outputs one line for each minute, and doesn't print the bell character
		        (ascii 007)
		    -m: mute -- don't play sounds when work/break is over
		    -w m: let work periods last m minutes (default is 25)
		    -b m: let break periods last m minutes (default is 5)
		    -h: print this message
	END
}

play_notification() {
	aplay -q /usr/lib/potato/notification.wav&
}

while getopts :sw:b:m opt; do
	case "$opt" in
	s)
		INTERACTIVE=false
	;;
	m)
		MUTE=true
	;;
	w)
		WORK=$OPTARG
	;;
	b)
		PAUSE=$OPTARG
	;;
	h|\?)
		show_help
		exit 1
	;;
	esac
done

time_left="%s%im %s"

if $INTERACTIVE; then
	time_left="\r$time_left"
else
	time_left="$time_left\n"
fi

rondas=$(sed /retomar/d $potatofile)
tomate="🍅"
while true
do
	if ! grep -q retomar $potatofile; then
		for ((i=$WORK; i>0; i--))
		do
			printf "$time_left" "🍅" $i "$rondas" | tee $potatofile
			pkill -RTMIN+28 "${STATUSBAR:-dwmblocks}"
			sleep 1m
		done
		rondas=$rondas$tomate

		! $MUTE && play_notification
		if $INTERACTIVE; then
			read -d '' -t 0.001
			echo -e "\a"
			siguente="Seguir trabajando"
			respuesta=$(printf "Descansar\nSeguir trabajando\nParar" | dmenu -i -p "🍅 acabado")
			[[ $respuesta = "Seguir trabajando" || -z $respuesta ]] && echo -e "retomar\n$rondas" > $potatofile && pkill -RTMIN+28 "${STATUSBAR:-dwmblocks}" && exit 1
			[[ $respuesta = "Parar" ]] && echo "" > $potatofile && pkill -RTMIN+28 "${STATUSBAR:-dwmblocks}" && exit 1
		fi
	fi

	sed -i /retomar/d $potatofile

	for ((i=$PAUSE; i>0; i--))
	do
		printf "$time_left" "💤" $i "$rondas" | tee $potatofile
		pkill -RTMIN+28 "${STATUSBAR:-dwmblocks}"
		sleep 1m
	done
	! $MUTE && play_notification

	if $INTERACTIVE; then
		read -d '' -t 0.001
		echo -e "\a"
		## TODO: respuesta para añadir tiempo reescribiendo las variables de work y rest
		respuesta=$(printf "Trabajar\nSeguir descansando\nParar" | dmenu -i -p "💤 acabado")
		[[ $respuesta = "Seguir descansando"  || -z $respuesta ]] && echo $rondas > $potatofile && pkill -RTMIN+28 "${STATUSBAR:-dwmblocks}" && exit 1
		[[ $respuesta = "Parar" ]] && echo "" > $potatofile && pkill -RTMIN+28 "${STATUSBAR:-dwmblocks}" && exit 1
	fi
done
